# Generated by Django 2.1.2 on 2019-03-18 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='fg_name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='league',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='rw_name',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
