# Generated by Django 2.1.2 on 2019-03-18 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20190317_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='fg_name',
            field=models.CharField(max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='rw_name',
            field=models.CharField(max_length=24, null=True),
        ),
    ]
