# Generated by Django 2.1.2 on 2019-03-18 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20190317_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='on_slate',
            field=models.BooleanField(default=False),
        ),
    ]
