# Generated by Django 2.1.2 on 2019-03-19 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_team_on_slate'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='home',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='opp',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
