# Generated by Django 2.1.2 on 2019-03-26 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_auto_20190318_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rw_name', models.CharField(max_length=124, null=True)),
                ('game_type', models.CharField(max_length=10, null=True)),
                ('order', models.IntegerField(default=0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Team')),
            ],
        ),
    ]
