# Generated by Django 2.1.2 on 2019-03-28 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_defaultorders'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkFactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runs', models.DecimalField(decimal_places=3, default=1, max_digits=10)),
                ('hr', models.DecimalField(decimal_places=3, default=1, max_digits=10)),
                ('h', models.DecimalField(decimal_places=3, default=1, max_digits=10)),
                ('double', models.DecimalField(decimal_places=3, default=1, max_digits=10)),
                ('triple', models.DecimalField(decimal_places=3, default=1, max_digits=10)),
                ('bb', models.DecimalField(decimal_places=3, default=1, max_digits=10)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='factor', to='teams.Team')),
            ],
        ),
        migrations.AlterField(
            model_name='defaultorders',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='teams.Team'),
        ),
    ]
