# Generated by Django 2.1.2 on 2019-04-22 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_auto_20190327_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
