# Generated by Django 2.1.2 on 2018-11-13 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betslip', '0002_auto_20181112_2040'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
