# Generated by Django 2.1.2 on 2018-12-17 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20181112_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='limit',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='max_deposit',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10),
        ),
    ]
