# Generated by Django 2.1.2 on 2019-03-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lineups',
            fields=[
                ('lu_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('p1', models.CharField(max_length=124, null=True)),
                ('p2', models.CharField(max_length=124, null=True)),
                ('c', models.CharField(max_length=124, null=True)),
                ('fB', models.CharField(max_length=124, null=True)),
                ('sB', models.CharField(max_length=124, null=True)),
                ('tB', models.CharField(max_length=124, null=True)),
                ('ss', models.CharField(max_length=124, null=True)),
                ('of1', models.CharField(max_length=124, null=True)),
                ('of2', models.CharField(max_length=124, null=True)),
                ('of3', models.CharField(max_length=124, null=True)),
                ('salary', models.IntegerField(default=0)),
                ('team1', models.CharField(max_length=10, null=True)),
                ('team2', models.CharField(max_length=10, null=True)),
                ('lu_type', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
