# Generated by Django 2.1.2 on 2019-03-14 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slate', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lineups',
            new_name='Lineup',
        ),
    ]
