# Generated by Django 2.1.2 on 2019-03-23 17:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0010_auto_20190323_1143'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('slate', '0004_stacks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stacks',
            new_name='StackPlayer',
        ),
    ]
