# Generated by Django 2.1.2 on 2019-03-23 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slate', '0005_auto_20190323_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stackplayer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
