# Generated by Django 2.1.2 on 2019-03-23 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0005_auto_20190318_2141'),
        ('slate', '0006_auto_20190323_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='stackplayer',
            name='user',
        ),
        migrations.AddField(
            model_name='stackplayer',
            name='stack',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='slate.Stack'),
            preserve_default=False,
        ),
    ]
