# Generated by Django 2.1.2 on 2019-03-23 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slate', '0007_auto_20190323_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stackplayer',
            name='stack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='slate.Stack'),
        ),
    ]
