# Generated by Django 2.1.2 on 2019-03-24 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slate', '0008_auto_20190323_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineup',
            name='all_teams',
            field=models.CharField(max_length=124, null=True),
        ),
    ]
