# Generated by Django 2.1.2 on 2019-03-25 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slate', '0009_lineup_all_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineup',
            name='pts',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
