# Generated by Django 2.1.2 on 2019-04-12 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slate', '0013_lineup_dedupe'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportlineup',
            name='dedupe',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
