# Generated by Django 2.1.2 on 2019-04-12 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slate', '0014_exportlineup_dedupe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportlineup',
            name='dedupe',
            field=models.BigIntegerField(),
        ),
    ]
