# Generated by Django 2.1.2 on 2019-04-12 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slate', '0015_auto_20190411_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineup',
            name='dedupe',
            field=models.CharField(max_length=124, null=True),
        ),
    ]
