# Generated by Django 2.1.2 on 2019-04-12 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slate', '0017_auto_20190411_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportlineup',
            name='dedupe',
            field=models.CharField(max_length=122, null=True),
        ),
    ]
