# Generated by Django 2.1.2 on 2019-04-18 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('slate', '0018_auto_20190411_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Punt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dkid', models.IntegerField()),
                ('name_id', models.CharField(max_length=124)),
                ('position', models.CharField(max_length=10)),
                ('salary', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
