# Generated by Django 2.1.2 on 2018-11-10 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('game_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('sport', models.CharField(max_length=24)),
                ('start_time', models.DateTimeField()),
                ('home', models.CharField(max_length=100)),
                ('away', models.CharField(max_length=100)),
                ('h_score', models.IntegerField(default=0, null=True)),
                ('a_score', models.IntegerField(default=0, null=True)),
                ('live_status', models.IntegerField(choices=[(0, 'pregame'), (1, 'live'), (2, 'complete')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Odds',
            fields=[
                ('odd_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('home', models.CharField(max_length=48, null=True)),
                ('type', models.CharField(choices=[('h_sprd', 'Home Spread'), ('a_sprd', 'Away Spread'), ('h_line', 'Home Line'), ('a_line', 'Away Line'), ('over', 'Over'), ('under', 'Under')], max_length=24)),
                ('price', models.IntegerField()),
                ('status', models.IntegerField(choices=[(0, 'pregame'), (1, 'lose'), (2, 'win'), (3, 'push')], default=0)),
            ],
            options={
                'verbose_name_plural': 'Odds',
            },
        ),
        migrations.CreateModel(
            name='OddsGroup',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=24)),
                ('h_score', models.IntegerField(default=0, null=True)),
                ('a_score', models.IntegerField(default=0, null=True)),
                ('handicap', models.DecimalField(decimal_places=1, max_digits=7)),
                ('total', models.DecimalField(decimal_places=1, max_digits=7, null=True)),
                ('live_status', models.IntegerField(choices=[(0, 'pregame'), (1, 'live'), (2, 'complete')], default=0)),
                ('a_line', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a_line', to='sportsbook.Odds')),
                ('a_sprd', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a_sprd', to='sportsbook.Odds')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sportsbook.Event')),
                ('h_line', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='h_line', to='sportsbook.Odds')),
                ('h_sprd', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='h_sprd', to='sportsbook.Odds')),
                ('over', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='over', to='sportsbook.Odds')),
                ('under', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='under', to='sportsbook.Odds')),
            ],
        ),
    ]
