# Generated by Django 2.1.2 on 2018-12-26 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsbook', '0002_event_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oddsgroup',
            name='live_status',
            field=models.IntegerField(choices=[(0, 'pregame'), (1, 'live'), (2, 'complete'), (3, 'canceled')], default=0),
        ),
    ]
