# Generated by Django 2.1.2 on 2018-12-27 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsbook', '0003_auto_20181226_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='live_status',
            field=models.IntegerField(choices=[(0, 'pregame'), (1, 'live'), (2, 'complete'), (3, 'canceled')], default=0),
        ),
    ]
