# Generated by Django 2.1.2 on 2018-12-29 15:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sportsbook', '0004_auto_20181227_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameOdds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handicap', models.DecimalField(decimal_places=1, max_digits=7)),
                ('h_line', models.IntegerField()),
                ('a_line', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=1, max_digits=7, null=True)),
                ('time', models.DateTimeField(default=datetime.datetime(2018, 12, 29, 15, 7, 23, 170885, tzinfo=utc))),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sportsbook.Event')),
            ],
            options={
                'verbose_name_plural': 'Odds',
            },
        ),
    ]
