# Generated by Django 2.1.2 on 2019-02-03 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportsbook', '0006_auto_20181229_0910'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameodds',
            options={'verbose_name_plural': 'Game Odds'},
        ),
        migrations.AlterField(
            model_name='oddsgroup',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='sportsbook.Event'),
        ),
    ]
