# Generated by Django 2.1.2 on 2019-02-03 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsbook', '0007_auto_20190203_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='oddsgroup',
            name='a_line_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='oddsgroup',
            name='a_sprd_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='oddsgroup',
            name='h_line_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='oddsgroup',
            name='h_sprd_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='oddsgroup',
            name='over_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='oddsgroup',
            name='under_price',
            field=models.IntegerField(null=True),
        ),
    ]
