# Generated by Django 2.2.4 on 2019-08-29 00:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sportsbook', '0008_auto_20190203_1559'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BetValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=1, max_digits=7, null=True)),
                ('handicap', models.DecimalField(decimal_places=1, max_digits=7)),
                ('placed_price', models.IntegerField()),
                ('type', models.CharField(max_length=24)),
                ('status', models.IntegerField(choices=[(0, 'pregame'), (1, 'lose'), (2, 'win'), (3, 'push')], default=0)),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sportsbook.Event')),
                ('odd', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sportsbook.Odds')),
                ('odd_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sportsbook.OddsGroup')),
            ],
        ),
        migrations.CreateModel(
            name='Slip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('divider', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('due', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('odds', models.ManyToManyField(blank=True, to='sportsbook.Odds')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlacedBet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placed_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('divider', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sum_odds', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('placed', models.DateTimeField()),
                ('collected', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('start_time', models.DateTimeField(null=True)),
                ('status', models.IntegerField(choices=[(0, 'active'), (1, 'lose'), (2, 'win'), (3, 'push')], default=0)),
                ('type', models.CharField(max_length=24)),
                ('odds', models.ManyToManyField(through='betslip.BetValue', to='sportsbook.Odds')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='betvalue',
            name='placed_bet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betslip.PlacedBet'),
        ),
    ]
