# Generated by Django 2.1.2 on 2018-11-13 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betslip', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placedbet',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='slip',
            name='shipping_address',
        ),
        migrations.AddField(
            model_name='placedbet',
            name='type',
            field=models.CharField(default=1, max_length=24),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='placedbet',
            name='status',
            field=models.IntegerField(choices=[(0, 'active'), (1, 'lose'), (2, 'win'), (3, 'push')], default=0),
        ),
    ]
