# Generated by Django 2.1.2 on 2018-12-17 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betslip', '0002_auto_20181112_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='placedbet',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
