# Generated by Django 2.1.2 on 2019-03-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dkid', models.IntegerField()),
                ('name', models.CharField(max_length=124)),
                ('name_id', models.CharField(max_length=124)),
                ('position', models.CharField(max_length=10)),
                ('second_pos', models.CharField(max_length=10)),
                ('game_info', models.CharField(max_length=124)),
                ('team', models.CharField(max_length=10)),
            ],
        ),
    ]
