# Generated by Django 2.2.4 on 2019-08-29 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0008_team_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='DkGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.CharField(max_length=10)),
                ('away', models.CharField(max_length=10)),
                ('sport', models.CharField(max_length=10)),
                ('start_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dkid', models.IntegerField()),
                ('dk_name', models.CharField(max_length=124)),
                ('rotowire_name', models.CharField(max_length=124)),
                ('fg_name', models.CharField(max_length=124)),
                ('name_id', models.CharField(max_length=124)),
                ('position', models.CharField(max_length=10)),
                ('second_pos', models.CharField(blank=True, max_length=10, null=True)),
                ('code_1', models.IntegerField(default=0)),
                ('code_2', models.IntegerField(default=0)),
                ('pts', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('salary', models.IntegerField(default=0)),
                ('game_info', models.CharField(max_length=124)),
                ('team', models.CharField(max_length=10)),
                ('starting', models.BooleanField(default=False)),
                ('order_pos', models.IntegerField(default=0)),
                ('throws', models.CharField(blank=True, max_length=5, null=True)),
                ('active', models.BooleanField(default=True)),
                ('bats', models.CharField(blank=True, max_length=1, null=True)),
                ('pown', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pitching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vs', models.IntegerField(choices=[(0, 'R'), (1, 'L'), (2, 'A'), (3, 'S')])),
                ('kk_p9', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bb_p9', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('kk_pbb', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('hr_p9', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('kp', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('avg', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('babip', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('whip', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('era', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('siera', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('woba', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('xfip', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fbp', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('gbp', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('hardp', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Batting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vs', models.IntegerField(choices=[(0, 'R'), (1, 'L'), (2, 'A'), (3, 'S')])),
                ('pa', models.IntegerField()),
                ('kp', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('avg', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('slg', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('ops', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('iso', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('woba', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('hard_p', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.Player')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.Team')),
            ],
        ),
    ]
