# Generated by Django 2.1.2 on 2019-03-12 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_auto_20190301_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vs', models.IntegerField(choices=[(0, 'R'), (1, 'L'), (2, 'A'), (3, 'S')])),
                ('kp', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('avg', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('slg', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ops', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('iso', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('woba', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('hard_p', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pitching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vs', models.IntegerField(choices=[(0, 'R'), (1, 'L'), (2, 'A'), (3, 'S')])),
                ('kk_p9', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bb_p9', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('kk_pbb', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('hr_p9', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('kp', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('avg', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('babip', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('siera', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.RenameField(
            model_name='player',
            old_name='name',
            new_name='dk_name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='lineup_pos',
        ),
        migrations.AddField(
            model_name='player',
            name='rotowire_name',
            field=models.CharField(default='a', max_length=124),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='starting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pitching',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Player'),
        ),
        migrations.AddField(
            model_name='batting',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Player'),
        ),
    ]
