# Generated by Django 2.1.2 on 2019-03-14 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_auto_20190312_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='salary',
            field=models.IntegerField(default=0),
        ),
    ]
