# Generated by Django 2.1.2 on 2019-03-17 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_player_order_pos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitching',
            name='era',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pitching',
            name='whip',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pitching',
            name='avg',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pitching',
            name='babip',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
