# Generated by Django 2.1.2 on 2019-03-18 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_auto_20190317_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='batting',
            name='pa',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='batting',
            name='avg',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='batting',
            name='iso',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='batting',
            name='ops',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='batting',
            name='slg',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='batting',
            name='woba',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
