# Generated by Django 2.1.2 on 2019-03-19 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_team_on_slate'),
        ('players', '0007_auto_20190317_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='batting',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.Team'),
        ),
        migrations.AlterField(
            model_name='batting',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.Player'),
        ),
    ]
