# Generated by Django 2.1.2 on 2019-03-19 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_auto_20190318_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='throws',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
