# Generated by Django 2.1.2 on 2019-03-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0009_player_throws'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='code_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='code_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='pts',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
