# Generated by Django 2.1.2 on 2019-03-26 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0010_auto_20190323_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='fg_name',
            field=models.CharField(default='a', max_length=124),
            preserve_default=False,
        ),
    ]
