# Generated by Django 2.1.2 on 2019-04-10 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0011_player_fg_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
