# Generated by Django 2.1.2 on 2019-05-28 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0012_player_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='bats',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
