# Generated by Django 2.1.2 on 2019-05-28 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0013_player_bats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='second_pos',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
