# Generated by Django 2.1.2 on 2019-05-29 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0014_auto_20190527_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='bats',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='second_pos',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='throws',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
