# Generated by Django 2.2.4 on 2019-08-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0015_auto_20190528_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitching',
            name='fbp',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pitching',
            name='gbp',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pitching',
            name='hardp',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pitching',
            name='woba',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pitching',
            name='xfip',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
